// ERA v1 — item data. Source of truth: ERA-v1-item-bank.md (Gate 1, signed off).
// Formats: L5 likert · E5 enjoyment · MC choice · FC forced choice · FT free text · ACK acknowledge

export const L5 = ["Strongly disagree", "Disagree", "Neither", "Agree", "Strongly agree"];
export const E5 = ["Would hate it", "Would dislike it", "Not fussed", "Would enjoy it", "Would love it"];

export const PARTS = [
  {
    id: "arrival",
    kicker: "Part one of nine",
    title: "Arrival",
    intro: "A few questions to set the scene. There are no scores here — just tell it straight.",
    items: [
      { id: "AR-1", format: "FT", short: true, text: "What should we call you?" },
      { id: "AR-2", format: "FT", text: "What do you do right now — and how long have you been doing it?" },
      { id: "AR-3", format: "FT", text: "What's the hardest part of your working life at the moment?" },
      { id: "AR-4", format: "FT", text: "Describe a genuinely good working day. What happened?" },
      { id: "AR-5", format: "MC", text: "What brought you here today?", options: ["Something has to change", "Curious about myself", "At a crossroads", "Someone sent me", "Just exploring"] },
      { id: "AR-6", format: "MC", text: "How's your energy about work lately?", options: ["Running on empty", "Flat", "Up and down", "Steady", "Genuinely good"] },
    ],
    glimmer: { visual: "dot", line: (a) => a["AR-3"] ? `You said the hardest part is: \u201C${trim(a["AR-3"], 90)}\u201D. We'll keep that in view the whole way through.` : "First mark on the map. We'll keep your answers in view the whole way through." },
  },
  {
    id: "think1",
    kicker: "Part two of nine",
    title: "How you think — patterns & numbers",
    intro: "Untimed puzzles. This is about how you move through a problem, not an IQ score — we don't do those.",
    items: [
      { id: "TH-1", format: "MC", dim: "num", key: "17", text: "What comes next: 2, 3, 5, 8, 12, __ ?", options: ["15", "16", "17", "18"] },
      { id: "TH-2", format: "MC", dim: "num", key: "1", text: "What comes next: 81, 27, 9, 3, __ ?", options: ["1", "0", "2", "1.5"] },
      { id: "TH-3", format: "MC", dim: "num", key: "52", text: "What comes next: 7, 10, 16, 28, __ ?", options: ["40", "46", "52", "56"] },
      { id: "TH-4", format: "MC", dim: "num", key: "180", text: "Which is the odd one out?", options: ["121", "144", "169", "180", "196"] },
      { id: "TH-5", format: "MC", dim: "num", key: "N", text: "Letters: B, E, H, K, __ ?", options: ["L", "M", "N", "O"] },
      { id: "TH-6", format: "MC", dim: "num", key: "66", text: "Start with 40. Halve it. Add 13. Double the result. What do you have?", options: ["53", "62", "66", "73"] },
      { id: "TH-7", format: "MC", dim: "spa", key: "A triangle", svg: "frames", text: "A sequence of frames: a circle inside a square \u2192 a square inside a triangle \u2192 what sits inside the circle?", options: ["A circle", "A square", "A triangle"] },
      { id: "TH-8", format: "MC", dim: "spa", key: "South", text: "You face north. You turn right, then turn 180\u00B0, then turn left. Which way are you facing?", options: ["North", "South", "East", "West"] },
    ],
    glimmer: { visual: "ring", line: () => "No scores yet. Just noticing how you move through a problem." },
  },
  {
    id: "think2",
    kicker: "Part three of nine",
    title: "How you think — words & logic",
    intro: "Same rules. Take the time you need.",
    items: [
      { id: "TH-9", format: "MC", dim: "verb", key: "Appointments", text: "Ledger is to entries as calendar is to __", options: ["Dates", "Appointments", "Pages", "Months"] },
      { id: "TH-10", format: "MC", dim: "verb", key: "Lasting", text: "Scarce is to abundant as fleeting is to __", options: ["Brief", "Lasting", "Rapid", "Rare"] },
      { id: "TH-11", format: "MC", dim: "verb", key: "Oak", text: "Which is the odd one out?", options: ["Copper", "Iron", "Oak", "Tin", "Zinc"] },
      { id: "TH-12", format: "MC", dim: "verb", key: "Table", text: "Which word does NOT fit before \u201Clight\u201D?", options: ["Moon", "Day", "Flash", "Table"] },
      { id: "TH-13", format: "MC", dim: "log", key: "Some flowers here are red", text: "All roses in this garden are red. Some flowers in this garden are roses. Which must be true?", options: ["All flowers here are red", "Some flowers here are red", "No flowers here are red", "None of these must be true"] },
      { id: "TH-14", format: "MC", dim: "log", key: "It did not rain", text: "If it rains, the match is cancelled. The match was not cancelled. Which must be true?", options: ["It rained", "It did not rain", "The match was played indoors", "None of these must be true"] },
      { id: "TH-15", format: "L5", dim: "approach", text: "I'd rather sit with a hard problem than be handed the answer." },
      { id: "TH-16", format: "L5", dim: "approach", text: "I often spot the pattern before I can explain it in words." },
    ],
    glimmer: { visual: "tiles", line: (a, s) => `You leant ${s.thinking.lean} in this section. We'll test that read as we go.` },
  },
  {
    id: "ei1",
    kicker: "Part four of nine",
    title: "How you read the room",
    intro: "Answer as you actually are, not as you'd like to be. The honest answer is the useful one.",
    items: [
      { id: "EI-SA1", format: "L5", domain: "sa", text: "I can usually name what I'm feeling while I'm still feeling it." },
      { id: "EI-SA2", format: "L5", domain: "sa", text: "I know which situations drain me before I'm in them." },
      { id: "EI-SA3", format: "L5", domain: "sa", reverse: true, text: "I'm often surprised by my own reactions." },
      { id: "EI-SA4", format: "MC", domain: "sa", scored: false, text: "You've just had blunt criticism of work you cared about. What's the first thing you notice?", options: ["The flaw in their argument", "A drop in my stomach", "The urge to explain", "Nothing much until later"] },
      { id: "EI-SA5", format: "L5", domain: "sa", text: "I could tell you what my bad days have in common." },
      { id: "EI-SO1", format: "L5", domain: "so", text: "I notice when someone has checked out of a conversation." },
      { id: "EI-SO2", format: "L5", domain: "so", text: "People tell me things they don't tell others." },
      { id: "EI-SO3", format: "L5", domain: "so", text: "I can read the mood of a room within a few minutes." },
      { id: "EI-SO4", format: "L5", domain: "so", reverse: true, text: "I misjudge how my words land." },
      { id: "EI-SO5", format: "MC", domain: "so", scored: false, text: "A colleague is quieter than usual this week. What's your honest, most likely move?", options: ["Ask them directly, in private", "Watch a bit longer", "Assume it's not my business", "Mention it to someone who knows them better"] },
    ],
    glimmer: { visual: "pair", line: () => "Half of emotional intelligence is just noticing. You've been noticing for ten questions." },
  },
  {
    id: "ei2",
    kicker: "Part five of nine",
    title: "How you handle the heat",
    intro: "Pressure, friction, and what you do with them.",
    items: [
      { id: "EI-SM1", format: "L5", domain: "sm", text: "When a plan collapses, I find my footing again quickly." },
      { id: "EI-SM2", format: "L5", domain: "sm", reverse: true, text: "I say things in frustration that I later regret." },
      { id: "EI-SM3", format: "L5", domain: "sm", text: "I can keep going on dull-but-important work." },
      { id: "QC-1", format: "L5", qc: "agree", text: "For this one, select \u201CAgree\u201D." },
      { id: "EI-SM4", format: "L5", domain: "sm", text: "Under pressure I get sharper, not scattered." },
      { id: "EI-SM5", format: "MC", domain: "sm", scored: false, text: "An email lands that makes your blood boil. What do you actually do?", options: ["Reply while it's hot", "Draft it, delete it, reply tomorrow", "Walk away and deal with it later", "Ring them instead"] },
      { id: "EI-RM1", format: "L5", domain: "rm", text: "I can disagree with someone without it turning personal." },
      { id: "EI-RM2", format: "L5", domain: "rm", text: "I find it easy to ask for help." },
      { id: "EI-RM3", format: "L5", domain: "rm", text: "I give hard feedback when it's needed, even when it's awkward." },
      { id: "EI-RM4", format: "L5", domain: "rm", reverse: true, text: "Conflict makes me withdraw." },
      { id: "EI-RM5", format: "MC", domain: "rm", scored: false, text: "Two people you work with are at odds and it's affecting everyone. You would most likely\u2026", options: ["Get them in a room together", "Speak to each separately first", "Stay out of it", "Raise it with whoever's in charge"] },
    ],
    glimmer: { visual: "compass", line: () => "You've just described how you carry yourself when it's hard. That's rarer knowledge than people think." },
  },
  {
    id: "riasec",
    kicker: "Part six of nine",
    title: "What pulls you",
    intro: "Quick ones. Gut answers — would you enjoy it?",
    shuffle: true,
    items: [
      { id: "RI-R1", format: "E5", code: "R", text: "Fixing a machine until it runs right" },
      { id: "RI-R2", format: "E5", code: "R", text: "Working outdoors with your hands" },
      { id: "RI-R3", format: "E5", code: "R", text: "Building something physical from a set of plans" },
      { id: "RI-R4", format: "E5", code: "R", text: "Getting good with tools or equipment" },
      { id: "RI-I1", format: "E5", code: "I", text: "Pulling a problem apart to find out why" },
      { id: "RI-I2", format: "E5", code: "I", text: "Reading the research until a question is settled" },
      { id: "RI-I3", format: "E5", code: "I", text: "Testing a hunch against real data" },
      { id: "RI-I4", format: "E5", code: "I", text: "Diagnosing a fault from its symptoms" },
      { id: "RI-A1", format: "E5", code: "A", text: "Deciding how something should look and feel" },
      { id: "RI-A2", format: "E5", code: "A", text: "Writing something strangers will read" },
      { id: "RI-A3", format: "E5", code: "A", text: "Finding an odd angle on an old problem" },
      { id: "RI-A4", format: "E5", code: "A", text: "Making something nobody asked for" },
      { id: "QC-2", format: "E5", qc: "hate", text: "For this one, select \u201CWould hate it\u201D." },
      { id: "RI-S1", format: "E5", code: "S", text: "Teaching someone until it finally clicks" },
      { id: "RI-S2", format: "E5", code: "S", text: "Sitting with someone through a rough patch" },
      { id: "RI-S3", format: "E5", code: "S", text: "Bringing people together who should know each other" },
      { id: "RI-S4", format: "E5", code: "S", text: "Mentoring someone a few steps behind you" },
      { id: "RI-E1", format: "E5", code: "E", text: "Pitching an idea to a sceptical room" },
      { id: "RI-E2", format: "E5", code: "E", text: "Negotiating until the deal lands" },
      { id: "RI-E3", format: "E5", code: "E", text: "Starting something from nothing" },
      { id: "RI-E4", format: "E5", code: "E", text: "Taking the lead when no one else will" },
      { id: "RI-C1", format: "E5", code: "C", text: "Bringing order to a messy system" },
      { id: "RI-C2", format: "E5", code: "C", text: "Keeping the records everyone else relies on" },
      { id: "RI-C3", format: "E5", code: "C", text: "Designing the process others follow" },
      { id: "RI-C4", format: "E5", code: "C", text: "Finishing the checklist. Completely." },
    ],
    glimmer: { visual: "petals", line: (a, s) => `Something keeps pulling you toward ${s.riasec.topPhrase}.` },
  },
  {
    id: "values",
    kicker: "Part seven of nine",
    title: "What you're for",
    intro: "What matters, and what you'd give up to keep it.",
    items: [
      { id: "VA-A1", format: "L5", value: "Achievement", text: "Being visibly good at what I do matters to me." },
      { id: "VA-A2", format: "L5", value: "Achievement", text: "I want my results to speak for themselves — and to be heard." },
      { id: "VA-P1", format: "L5", value: "Power", text: "I want a real say in how things are run." },
      { id: "VA-P2", format: "L5", value: "Power", text: "Influence matters more to me than approval." },
      { id: "VA-SE1", format: "L5", value: "Security", text: "Stability is worth more to me than excitement." },
      { id: "VA-SE2", format: "L5", value: "Security", text: "I plan for the worst so it never surprises me." },
      { id: "VA-ST1", format: "L5", value: "Stimulation", text: "I get restless when life is too predictable." },
      { id: "VA-ST2", format: "L5", value: "Stimulation", text: "New beats comfortable, most days." },
      { id: "VA-SD1", format: "L5", value: "Self-direction", text: "I'd trade money for freedom in how I work." },
      { id: "VA-SD2", format: "L5", value: "Self-direction", text: "Being told how to do my job grates on me." },
      { id: "VA-U1", format: "L5", value: "Universalism", text: "My work should leave things better than I found them." },
      { id: "VA-U2", format: "L5", value: "Universalism", text: "Fairness matters to me even when it costs me." },
      { id: "VA-F1", format: "FC", a: { text: "A secure role I know inside out", value: "Security" }, b: { text: "An uncertain role that might be extraordinary", value: "Stimulation" }, text: "If you had to pick one:" },
      { id: "VA-F2", format: "FC", a: { text: "Being recognised as the best", value: "Achievement" }, b: { text: "Knowing the work helped someone", value: "Universalism" }, text: "If you had to pick one:" },
      { id: "VA-F3", format: "FC", a: { text: "Authority over the direction", value: "Power" }, b: { text: "Freedom over my own path", value: "Self-direction" }, text: "If you had to pick one:" },
      { id: "VA-F4", format: "FC", a: { text: "More money, less say", value: "Security" }, b: { text: "More say, less money", value: "Self-direction" }, text: "If you had to pick one:" },
      { id: "VA-F5", format: "FC", a: { text: "The safe plan that works", value: "Security" }, b: { text: "The bold plan that might not", value: "Stimulation" }, text: "If you had to pick one:" },
      { id: "VA-F6", format: "FC", a: { text: "A calm year", value: "Security" }, b: { text: "A remarkable year", value: "Achievement" }, text: "If you had to pick one:" },
    ],
    glimmer: { visual: "beam", line: (a, s) => `When forced to choose, you chose ${s.values.fcPhrase}. Remember that next time someone offers you the opposite.` },
  },
  {
    id: "big5",
    kicker: "Part eight of nine",
    title: "How you work",
    intro: "Last battery. How you actually operate, day to day.",
    items: [
      { id: "BF-O1", format: "L5", trait: "O", text: "I hunt out ideas well beyond my own field." },
      { id: "BF-O2", format: "L5", trait: "O", reverse: true, text: "Abstract conversations bore me." },
      { id: "BF-O3", format: "L5", trait: "O", text: "I enjoy work I've never done before." },
      { id: "BF-O4", format: "L5", trait: "O", reverse: true, text: "I'd rather perfect the familiar than attempt the new." },
      { id: "BF-O5", format: "L5", trait: "O", text: "I make connections other people miss." },
      { id: "BF-C1", format: "L5", trait: "C", text: "I finish what I start, even after the shine wears off." },
      { id: "BF-C2", format: "L5", trait: "C", text: "My systems are organised enough that someone else could use them." },
      { id: "BF-C3", format: "L5", trait: "C", reverse: true, text: "Deadlines have a habit of sneaking up on me." },
      { id: "BF-C4", format: "L5", trait: "C", text: "I plan first and act second." },
      { id: "BF-C5", format: "L5", trait: "C", reverse: true, text: "I lose steam on long projects." },
      { id: "BF-E1", format: "L5", trait: "E", text: "Groups give me energy." },
      { id: "BF-E2", format: "L5", trait: "E", text: "I speak up early in a discussion." },
      { id: "BF-E3", format: "L5", trait: "E", reverse: true, text: "I need quiet to recharge after being social." },
      { id: "BF-E4", format: "L5", trait: "E", reverse: true, text: "I'd rather listen than lead the conversation." },
      { id: "BF-E5", format: "L5", trait: "E", text: "Meeting new people comes easily to me." },
      { id: "BF-A1", format: "L5", trait: "A", text: "I look for what's right in another view before I argue with it." },
      { id: "BF-A2", format: "L5", trait: "A", text: "People would call me easy to work with." },
      { id: "BF-A3", format: "L5", trait: "A", reverse: true, text: "I push my point until it wins." },
      { id: "BF-A4", format: "L5", trait: "A", text: "I give people the benefit of the doubt." },
      { id: "BF-A5", format: "L5", trait: "A", reverse: true, text: "Being right matters more to me than getting along." },
      { id: "BF-N1", format: "L5", trait: "N", reverse: true, text: "Small setbacks stay with me longer than they should." },
      { id: "BF-N2", format: "L5", trait: "N", text: "I stay calm when things go sideways." },
      { id: "BF-N3", format: "L5", trait: "N", reverse: true, text: "I worry about things I can't control." },
      { id: "BF-N4", format: "L5", trait: "N", text: "Criticism rolls off me fairly quickly." },
      { id: "BF-N5", format: "L5", trait: "N", reverse: true, text: "My confidence can dip without warning." },
    ],
    glimmer: { visual: "bars", line: () => "Nearly there. The picture is almost whole." },
  },
  {
    id: "mirror",
    kicker: "Part nine of nine",
    title: "The mirror",
    intro: "Last few. These go straight into your report, in your own words.",
    items: [
      { id: "MI-1", format: "FT", text: "What has no one ever told you about your work that you needed to hear?" },
      { id: "MI-2", format: "MC", text: "If nothing changed for five years, how would that sit with you?", options: ["Fine — I'm where I should be", "Uneasy", "Honestly, unbearable", "I'd have left long before"] },
      { id: "MI-3", format: "FT", text: "Complete the sentence: \u201CAt my best, I'm the kind of person who\u2026\u201D" },
      { id: "MI-4", format: "FT", optional: true, text: "Anything you want the report to know that we didn't ask?" },
      { id: "MI-C", format: "ACK", text: "Your answers stay on this device. Your report is generated from them and belongs to you. Nothing is shared, sold, or stored on our servers." },
    ],
    glimmer: null,
  },
];

export const RIASEC_PHRASES = {
  R: "making and fixing real things",
  I: "understanding why, not just what",
  A: "making something that didn't exist before",
  S: "people, and what they could become",
  E: "starting things and bringing others with you",
  C: "order, and the quiet craft of getting it right",
};

function trim(s, n) { return s.length > n ? s.slice(0, n).trim() + "\u2026" : s; }
