[build]
  publish = "."
  command = "npm run build"

[functions]
  node_bundler = "esbuild"

[[headers]]
  for = "/sw.js"
  [headers.values]
    Cache-Control = "no-cache"

[[headers]]
  for = "/*"
  [headers.values]
    Permissions-Policy = "microphone=(self), camera=(self)"
